### PR TITLE
Draft: Default section prop and a couple of tweak / fixes.

### PR DESCRIPTION
**Pull request by Julioevm**
I PR adds:

- Default section prop.
- Optional Recent and Recent Function props.
- A fix for the width calculation, I still have to test this, I was seeing some weird behaviour with the original.

### CODE REVIEW

**Comment by Julioevm** [comment]
@woodybury I'm not able to test out these changes, the example app is not connecting to my device, let me know if you can give it a try, thanks!

**Comment by woodybury** [comment]
@Julioevm nice! Thanks for this. Looks good albeit one issue:

`enabledCategories = categories.values()['key']` yields empty obj? I think .values() returns an iterator? If you use a map instead that seems to work, e.g. `categories.map(c => c.key)`. Either way can you move the calc out of the default props, maybe export a const `categoryKeys` from the constants file?

Other than that it's testing well. Nice catch w/ the width! 

Can you update example on the readme and example app?

```
                onChangeRecent={setRecent} // callback to update recent storage - arr of emoji objs
                // backgroundColor={'#000'} // optional custom bg color
                // enabledCategories={['emotion', 'emojis', 'activities', 'flags', 'food', 'places', 'nature']}
                // defaultCategory={'food'} // optional custom default category
```
`

**Comment by Julioevm** [comment]
@woodybury Applied your suggestions, let me know if there's anything else!

**Comment by woodybury** [comment]
@Julioevm great published 1.1.6 https://www.npmjs.com/package/rn-emoji-picker

**Pull request merged**
